### ISSUE TITLE
[npmjs.com bug] Repository/homepage link on npmjs.com doesn't lead here.

### ISSUE THREAD

**Issue by fuadop** [Codecademy/Konamimojisplosion#4]
![Screenshot from 2022-05-30 10-13-31](https://user-images.githubusercontent.com/65264054/170959710-5f494656-0481-414f-a4a9-d0b0e049fd36.png)
The home page and repository links on npmjs.com leads to https://github.com/codecademy/client-modules instead.

**Comment by fuadop** [comment]
From the looks of things.. Looks like the npmjs.com deploy is a bit behind this repo ? the [package.json](https://github.com/Codecademy/Konamimojisplosion/blob/main/package.json) says version 0.5.1meanwhile on npmjs.com it says 0.3.2.

**Comment by JoshuaKGoldberg** [comment]
Very weird. Looks like it's fixed now though. Thanks for the report!
